language: node_js
os: linux
dist: xenial

node_js:
  - "node"

notifications:
  email:
    recipients:
      - github@stejsoftware.com
    on_failure: always
    on_success: change

env:
  - SLACK_CLIENT_ID=000.000
    SLACK_CLIENT_SECRET=testtest
    SLACK_SIGNING_SECRET=testtest
    SLACK_APP_ID=A01EC7LC547
